### ISSUE TITLE
[Farming Valley] Wirecutters missing from general store (includes code fix)

### ISSUE THREAD

**Issue by HebaruSan** [Kehaan/MadPack-2#1]
Hi @Kehaan,

(Sorry for posting here, but I don't have a Curseforge/Twitch account and would prefer not to create one. I've been enjoying Farming Valley, and the recent update must mean that you still look at it occasionally.)

## Problem

In Farming Valley, the Immersive Engineering wirecutters can't be crafted, but the tooltip says they can be bought at the general store. However, the general store doesn't actually have them.

## Cause

`ShipItems.zs` removes two IE tool recipes here:

```zs
recipes.remove(<immersiveengineering:tool:1>);
recipes.remove(<immersiveengineering:tool:2>);
```

And then adds two tools to the store here:

```zs
mods.harvestfestival.Shops.addPurchasable("harvestfestival:general",<immersiveengineering:tool>, 2500);
mods.harvestfestival.Shops.addPurchasable("harvestfestival:general",<immersiveengineering:tool:2>, 2500);
```

I think the first line is missing `:1` to add the same tool that was removed before, and if this is the wirecutters, then that would explain why they're missing.

## Suggestion

If I could submit a pull request, I'd change it to this:

```zs
mods.harvestfestival.Shops.addPurchasable("harvestfestival:general",<immersiveengineering:tool:1>, 2500);
mods.harvestfestival.Shops.addPurchasable("harvestfestival:general",<immersiveengineering:tool:2>, 2500);
```

After making this change on my server and client, I see the wirecutters in the store.

Cheers!

**Comment by Kehaan** [comment]
Thanks for this.

However if doing it like you write and removing the tool> you cant buy the hammer. Engineers Hammer, as that one does that :) So only having :1> and :2> would loose the Engineers Hammer.

But will fix it, so both can be brought. Will push update later today :)
